// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiEDQbNvrpfbI9hN7xwK5xgcUpi14L1jg',
    appId: '1:1016514483924:web:be1bca6ed143dbe7ce0d41',
    messagingSenderId: '1016514483924',
    projectId: 'do-with-me-7c67c',
    authDomain: 'do-with-me-7c67c.firebaseapp.com',
    storageBucket: 'do-with-me-7c67c.appspot.com',
    measurementId: 'G-5HLX9FLP2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXffDKGqQGQxo51-QSvQdvWpV2GE7hLMw',
    appId: '1:1016514483924:android:1a1697f6203cf505ce0d41',
    messagingSenderId: '1016514483924',
    projectId: 'do-with-me-7c67c',
    storageBucket: 'do-with-me-7c67c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdwuPYc46aRclLcBwco2yLup0lvzwXwqo',
    appId: '1:1016514483924:ios:5c07f2fb680ccc05ce0d41',
    messagingSenderId: '1016514483924',
    projectId: 'do-with-me-7c67c',
    storageBucket: 'do-with-me-7c67c.appspot.com',
    androidClientId: '1016514483924-qtklmvucuvu7jno5k2klkpa3ae11d81c.apps.googleusercontent.com',
    iosClientId: '1016514483924-snkkuulo8ik7plo90ktagoqguqgipfoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.doWithMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdwuPYc46aRclLcBwco2yLup0lvzwXwqo',
    appId: '1:1016514483924:ios:5c07f2fb680ccc05ce0d41',
    messagingSenderId: '1016514483924',
    projectId: 'do-with-me-7c67c',
    storageBucket: 'do-with-me-7c67c.appspot.com',
    androidClientId: '1016514483924-qtklmvucuvu7jno5k2klkpa3ae11d81c.apps.googleusercontent.com',
    iosClientId: '1016514483924-snkkuulo8ik7plo90ktagoqguqgipfoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.doWithMe',
  );
}
